apps/equipments/urls.py
from django.urls import path
from .views import (
    equipment_detail,
    equipment_history,
    equipment_open_work,
)

app_name = 'equipments'

urlpatterns = [
    path('equipments/<int:equipment_id>/', equipment_detail, name='equipment'),
    path('equipments/<int:equipment_id>/history', equipment_history, name='equipment_history'),
    path('equipments/<int:equipment_id>/open_work', equipment_open_work, name='equipment_open_work'),
]

apps/work_order/urls.py
from django.urls import path
from .views import work, work_start, work_finish

app_name = 'work_order'

urlpatterns = [
    path('work/<int:work_id>/', work, name='work'),
    path('work/start', work_start, name='work_start'),
    path('work/<int:work_id>/finish', work_finish, name='work_finish'),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import request_error, request_success


admin.site.index_title = 'Área de Administração'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('equipments.urls')),
    path('', include('work_order.urls')),
    path('success', request_success, name='request_success'),
    path('error', request_error, name='request_error'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/work_order/models.py
from django.db import models
from django.contrib.auth.models import User
from equipments.models import Equipment

SERVICES = (
    (1, 'Manutenção corretiva'),
    (2, 'Manutenção preventiva'),
    (3, 'Calibração'),
    (4, 'Treinamento'),
    (5, 'Instalação'),
)

STATUS = (
    (1, 'Aberto'),
    (2, 'Em atendimento'),
    (3, 'Finalizado'),
    (4, 'Impossível realizar'), # apenas gestor
)


class WorkOrder(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Criado em')
    checkin = models.DateTimeField(blank=True, null=True, verbose_name='Checkin')
    service = models.IntegerField(choices=SERVICES, default=1, verbose_name='Tipo de serviço')
    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE, related_name='equipment_works', verbose_name='Equipamento')
    requester = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='requester_orders', verbose_name='Solicitante')
    request_description = models.TextField(blank=True, verbose_name='Descrição')
    job_description = models.TextField(blank=True, help_text='Útil para inspeção futura', verbose_name='Solução')
    status = models.IntegerField(choices=STATUS, default=1, verbose_name='Status')
    worker = models.ForeignKey(User, blank=True, null=True, on_delete=models.DO_NOTHING, related_name='worker_orders', verbose_name='Colaborador')
    checkout = models.DateTimeField(blank=True, null=True, verbose_name='Checkout')

    def __str__(self):
        return f'{ self.get_service_display() } - {self.created_at.strftime("%d/%m/%Y %H:%M:%S")}'

apps/work_order/forms.py
from django import forms
from .models import WorkOrder


class WorkForms(forms.ModelForm):

    class Meta:
        model = WorkOrder
        fields = ['job_description']

        widgets = {
            'job_description': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': '3',
            }),
        }

    def clean(self):
        return self.cleaned_data

apps/work_order/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone

from .models import WorkOrder
from .forms import WorkForms


@login_required(redirect_field_name='next', login_url='/admin/login/')
def work(request: object, work_id: int):
    '''Exibe ordem de serviço com formulário'''
    instance = get_object_or_404(WorkOrder, pk=work_id)
    context = {
        'page_title': 'Ordem de serviço',
        'form': WorkForms(instance=instance),
        'work': instance,
    }
    return render(request, 'work_order/work.html', context)


@login_required(redirect_field_name='next', login_url='/admin/login/')
def work_start(request: object):
    '''Começa ordem de serviço'''
    if request.method == 'POST':
        work_id = request.POST.get('work_order')
        instance = get_object_or_404(WorkOrder, pk=work_id)
        instance.worker = request.user
        instance.status = 2
        if not instance.checkin:
            instance.checkin = timezone.now()
        instance.save()
    return redirect('work_order:work', work_id=work_id)


@login_required(redirect_field_name='next', login_url='/admin/login/')
def work_finish(request: object, work_id: int):
    '''Finaliza ordem de serviço'''
    instance = get_object_or_404(WorkOrder, pk=work_id)
    if request.method == 'POST':
        form = WorkForms(request.POST, instance=instance)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.status = 3
            instance.checkout = timezone.now()
            instance.save()
            messages.success(request, 'Ordem de serviço finalizada com sucesso!')
    return redirect('equipments:equipment', equipment_id=instance.equipment.id)

templates/work_order/work.html
{% extends '../partials/__base.html' %}
{% load static %}

{% block page_title %} {{ page_title }} {% endblock page_title %}

{% block content %}
    <main
        class="p-5"
        style="min-height: 100vh; display: flex; flex-direction: column; justify-content: space-between;"
    >
        <h2 align="center">{{ page_title }}</h2>

        <div
            class="card mb-4 p-0"
            style="width: 100%; max-width: 600px; margin: 0 auto 0;"
        >
            <h5 class="card-header">Equipamento: {{ work.equipment }} ({{ work.get_service_display }})</h5>

            <div class="card-body">
                <p class="card-text"><b>Solicitante:</b> {{ work.requester }}</p>
                <p class="card-text"><b>Descrição:</b> {{ work.request_description }}</p>
                <p class="card-text">
                    <b>Início:</b>
                    {{ work.checkin|date:'d/m/Y H:i' }}
                </p>
            </div>
        </div>

        <form
            action="{% url 'work_order:work_finish' work_id=work.id %}"
            class="pt-3 row"
            method="POST"
            style="max-width: 600px; margin: 0 auto 0;"
        >
            {% csrf_token %}

            {% for field in form %}
                <div class="mb-3">
                    <label
                        for="{{ field.id_for_label }}"
                        class="form-label"
                    >
                        {{ field.label }}
                    </label>

                    {{ field }}
                </div>
            {% endfor %}

            <div>
                <button
                    class="btn btn-lg btn-primary w-100"
                    type="submit"
                >
                    FINALIZAR
                </button>

                <a
                    href="{% url 'equipments:equipment' equipment_id=work.equipment.id %}"
                    class="btn btn-lg btn-secondary w-100 mt-4"
                >
                    Voltar
                </a>
            </div>
        </form>

        <p class="text-center text-muted mt-3">
            © SIGEMH – {% now "Y" %}
        </p>
    </main>

{% endblock content %}