apps/equipments/urls.py
from django.urls import path
from .views import (
    equipment_detail,
    equipment_history,
    equipment_open_work,
)

app_name = 'equipments'

urlpatterns = [
    path('equipments/<int:equipment_id>/', equipment_detail, name='equipment'),
    path('equipments/<int:equipment_id>/history', equipment_history, name='equipment_history'),
    path('equipments/<int:equipment_id>/open_work', equipment_open_work, name='equipment_open_work'),
]

apps/work_order/urls.py
from django.urls import path
from .views import work, work_start, work_finish

app_name = 'work_order'

urlpatterns = [
    path('work/<int:work_id>/', work, name='work'),
    path('work/start', work_start, name='work_start'),
    path('work/<int:work_id>/finish', work_finish, name='work_finish'),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import request_error, request_success


admin.site.index_title = 'Área de Administração'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('equipments.urls')),
    path('', include('work_order.urls')),
    path('success', request_success, name='request_success'),
    path('error', request_error, name='request_error'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/equipments/models.py
import os, uuid
from django.db import models
from django.utils.safestring import mark_safe
from core.models import Location
from equipments.methods.handle_image import generate_equipment_qrcode

from django.db.models.signals import post_save
from django.dispatch import receiver

PRIORITY = (
    (1, 'Baixo'),
    (2, 'Medio'),
    (3, 'Alto'),
    (4, 'Urgente'),
)

def create_id(length=5):
    uuid_str = str(uuid.uuid4())
    return uuid_str[:length]


def equipment_model_upload_to(instance, filename) -> str:
    '''Upload do arquivo para caminho especifico'''
    file_extension = filename.split('.')[-1]
    new_filename = f'{create_id()}.{file_extension}'
    return os.path.join('equipment_models', instance.id, new_filename)


class Manufacturer(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Criado em')
    name = models.CharField(max_length=75, unique=True, verbose_name='Nome')
    is_active = models.BooleanField(default=True, verbose_name='Ativo')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Editado em')

    def __str__(self):
        return self.name


class EquipmentType(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Criado em')
    name = models.CharField(max_length=75, unique=True, verbose_name='Nome')
    description = models.TextField(max_length=75, null=True, blank=True, verbose_name='Descrição')
    mean_failure_time = models.PositiveSmallIntegerField(default=2010, verbose_name='Tempo médio de falha (meses)')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Editado em')

    def __str__(self):
        return self.name


class EquipmentModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Criado em')
    name = models.CharField(max_length=75, unique=True, verbose_name='Nome')
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE, related_name='manufacturer_equipments', verbose_name='Fabricante')
    equipment_type = models.ForeignKey(EquipmentType, on_delete=models.CASCADE, related_name='type_equipments', verbose_name='Tipo de equipamento')
    operating_instructions = models.FileField(blank=True, upload_to='equipment_model_upload_to', verbose_name='Instruções de operação')
    image_1 = models.ImageField(blank=True, upload_to='equipment_model_upload_to', verbose_name='Foto 1')
    image_2 = models.ImageField(blank=True, upload_to='equipment_model_upload_to', verbose_name='Foto 2')
    image_3 = models.ImageField(blank=True, upload_to='equipment_model_upload_to', verbose_name='Foto 3')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Editado em')

    def __str__(self):
        return self.name


class Equipment(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Criado em')
    equipment_model = models.ForeignKey(EquipmentModel, on_delete=models.CASCADE, related_name='model_equipments', verbose_name='Modelo do equipamento')
    year_of_manufacture = models.PositiveSmallIntegerField(default=2010, verbose_name='Ano de fabricação')
    acquisition_date = models.DateField(blank=True, null=True, verbose_name='Data de aquisição')
    serial_number = models.CharField(max_length=75, unique=True, verbose_name='Número de série')
    patrimony = models.CharField(max_length=75, unique=True, verbose_name='Número de patrimônio')
    location = models.ForeignKey(Location, on_delete=models.DO_NOTHING, null=True, blank=True, verbose_name='Localização')
    accident_history = models.BooleanField(default=True, verbose_name='Histórico de acidente')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Editado em')
    work_priority = models.PositiveSmallIntegerField(choices=PRIORITY, default=1, verbose_name='Prioridade')
    warranty_expiration = models.DateField(blank=True, null=True, verbose_name='Vencimento da garantia')
    external_maintenance = models.BooleanField(default=False, verbose_name='Manutenção externa')
    qr_code = models.ImageField(blank=True, upload_to='equipments/qr_code', verbose_name='QR Code')
    is_active = models.BooleanField(default=True, verbose_name='Ativo')

    def __str__(self):
        return f'{self.equipment_model} - {self.patrimony}'

    def save_qr_code(self):
        qrcode_result = generate_equipment_qrcode(self)
        self.qr_code = qrcode_result
        print('xxx')
        self.save()

    def show_qr_code(self):
        return mark_safe(f'''
			<a href="{ self.qr_code.url }" target="_blank">
                See
			</a>'''
		)

apps/work_order/models.py
from django.db import models
from django.contrib.auth.models import User
from equipments.models import Equipment

SERVICES = (
    (1, 'Manutenção corretiva'),
    (2, 'Manutenção preventiva'),
    (3, 'Calibração'),
    (4, 'Treinamento'),
    (5, 'Instalação'),
)

STATUS = (
    (1, 'Aberto'),
    (2, 'Em atendimento'),
    (3, 'Finalizado'),
    (4, 'Impossível realizar'), # apenas gestor
)


class WorkOrder(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Criado em')
    checkin = models.DateTimeField(blank=True, null=True, verbose_name='Checkin')
    service = models.IntegerField(choices=SERVICES, default=1, verbose_name='Tipo de serviço')
    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE, related_name='equipment_works', verbose_name='Equipamento')
    requester = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='requester_orders', verbose_name='Solicitante')
    request_description = models.TextField(blank=True, verbose_name='Descrição')
    job_description = models.TextField(blank=True, help_text='Útil para inspeção futura', verbose_name='Solução')
    status = models.IntegerField(choices=STATUS, default=1, verbose_name='Status')
    worker = models.ForeignKey(User, blank=True, null=True, on_delete=models.DO_NOTHING, related_name='worker_orders', verbose_name='Colaborador')
    checkout = models.DateTimeField(blank=True, null=True, verbose_name='Checkout')

    def __str__(self):
        return f'{ self.get_service_display() } - {self.created_at.strftime("%d/%m/%Y %H:%M:%S")}'

apps/equipments/forms.py
from django import forms
from .models import Equipment
from work_order.models import WorkOrder


class SelectWorkForms(forms.ModelForm):
    # equipment = forms.CharField(
    #     disabled=True,
    #     widget=forms.TextInput(attrs={'class': 'form-control'})
    # )
    work_order = forms.ModelChoiceField(
        queryset=None,
        widget=forms.Select(attrs={'class': 'form-select'})
    )

    class Meta:
        model = Equipment
        # fields = ['equipment', 'work_order']
        fields = ['work_order']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        instance = kwargs.get('instance')
        if instance:
            # self.fields['equipment'].initial = instance
            self.fields['work_order'].queryset = instance.equipment_works.all()
            # self.fields['work_order'].queryset = instance.equipment_works.filter(status=1)

    def clean(self):
        return self.cleaned_data


class OpenWorkForms(forms.ModelForm):

    class Meta:
        model = WorkOrder
        fields = ['request_description']

        widgets = {
            'request_description': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': '3',
                'required': True
            }),
        }

    def clean(self):
        return self.cleaned_data

apps/equipments/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from .models import Equipment
from .forms import OpenWorkForms, SelectWorkForms


@login_required(redirect_field_name='next', login_url='/admin/login/')
def equipment_detail(request: object, equipment_id: int):
    '''Selecionar ordem de serviço do equipamento'''
    equipment = get_object_or_404(Equipment, pk=equipment_id)

    if not request.user.profile.engineering_team:
        return redirect('equipments:equipment_open_work', equipment_id=equipment_id)

    context = {
        'page_title': 'Selecione a ordem de serviço do equipamento',
        'form': SelectWorkForms(instance=equipment),
        'equipment': equipment,
    }
    return render(request, 'equipments/equipment.html', context)


@login_required(redirect_field_name='next', login_url='/admin/login/')
def equipment_history(request: object, equipment_id: int):
    '''Histórico de ordens de serviço do equipamento'''
    equipment = get_object_or_404(Equipment, pk=equipment_id)
    context = {
        'page_title': 'Histórico do equipamento',
        'works': equipment.equipment_works.all(),
        'equipment': equipment,
    }
    return render(request, 'equipments/equipment_history.html', context)


@login_required(redirect_field_name='next', login_url='/admin/login/')
def equipment_open_work(request: object, equipment_id: int):
    '''Abrir ordem de serviço para o equipamento'''
    equipment = get_object_or_404(Equipment, pk=equipment_id)
    # has_works = equipment.equipment_works.filter(status=1, service=1).exists()
    has_works = False

    if request.method == 'POST':
        form = OpenWorkForms(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.equipment = equipment
            instance.requester = request.user
            instance.save()
            return JsonResponse({'message': 'ok'})

    context = {
        'page_title': 'Abrir ordem de serviço',
        'form': OpenWorkForms(),
        'equipment': equipment,
        'submit_disabled': has_works
    }

    if has_works:
        messages.warning(request, 'Equipamento já possui ordem de serviço em aberto')
    return render(request, 'equipments/equipment_open_work.html', context)

templates/equipments/equipment.html
{% extends '../partials/__base.html' %}
{% load static %}

{% block page_title %} {{ page_title }} {% endblock page_title %}

{% block content %}
    <main
        class="p-5"
        style="min-height: 100vh; display: flex; flex-direction: column; justify-content: space-between;"
    >
        {% include "../partials/__messages.html" %}

        <h2 align="center">{{ page_title }}</h2>

        <div
            class="card mb-4 p-0"
            style="width: 100%; max-width: 600px; margin: 0 auto 0;"
        >
            <h5 class="card-header">Equipamento: {{ equipment.equipment_model }}</h5>

            <div class="card-body">
                <h5 class="card-title mb-3">Nº de patrimônio: {{ equipment.patrimony }}</h5>
                <p class="card-text">Localização: {{ equipment.location|default_if_none:"---" }}</p>
                <p class="card-text">Nº de série: {{ equipment.serial_number }}</p>
                <p class="card-text">Histórico de acidentes: {{ equipment.accident_history|yesno:"Sim,Não" }}</p>
            </div>
        </div>

        <form
            action="{% url 'work_order:work_start' %}"
            class="pt-3 row w-100"
            method="POST"
            style="max-width: 600px; margin: 0 auto 0;"
        >
            {% csrf_token %}

            {% for field in form %}
                <div class="mb-3">
                    <label
                        for="{{ field.id_for_label }}"
                        class="form-label"
                    >
                        {{ field.label }}
                    </label>

                    {{ field }}
                </div>
            {% endfor %}

            <div>
                <button
                    class="btn btn-lg btn-primary w-100"
                    type="submit"
                >
                    SELECIONAR
                </button>

                <a href="./history" class="btn btn-lg btn-secondary w-100 mt-4">
                    Histórico
                </a>
            </div>
        </form>

        <p class="text-center text-muted mt-3">
            © SIGEMH – {% now "Y" %}
        </p>
    </main>

{% endblock content %}

templates/equipments/equipment_history.html
{% extends '../partials/__base.html' %}
{% load static %}

{% block page_title %} {{ page_title }} {% endblock page_title %}

{% block content %}
    <main
        class="p-5"
        style="min-height: 100vh; display: flex; flex-direction: column; justify-content: space-between;"
    >
        <h2 align="center">{{ page_title }}</h2>

        <div
            class="pt-3 row"
            style="
                width: 100%;
                max-width: 600px;
                margin: 0 auto 0;
            "
        >
            {% csrf_token %}

            {% for work in works %}
                <div class="card mb-4 p-0">
                    <h5 class="card-header">{{ work }}</h5>

                    <div class="card-body">
                        <p class="card-text">Solicitante: {{ work.requester }}</p>
                        <p class="card-text">Descrição: {{ work.request_description }}</p>
                        <p class="card-text">Solução: {{ work.job_description|default:"---" }}</p>
                        <span class="badge bg-secondary">{{ work.get_status_display }}</span>
                    </div>
                </div>
            {% endfor %}

            <div class="p-0"">
                <a href="./" class="btn btn-lg btn-primary w-100">
                    Voltar
                </a>
            </div>

        </div>

        <p class="text-center text-muted mt-3">
            © SIGEMH – {% now "Y" %}
        </p>
    </main>

{% endblock content %}

templates/equipments/equipment_open_work.html
{% extends '../partials/__base.html' %}
{% load static %}

{% block page_title %} {{ page_title }} {% endblock page_title %}

{% block content %}
    <main
        class="p-5"
        style="min-height: 100vh; display: flex; flex-direction: column; justify-content: space-between;"
    >
        {% include "../partials/__messages.html" %}

        <h2 align="center">{{ page_title }}</h2>

        <div
            class="card mb-4 p-0"
            style="width: 100%; max-width: 600px; margin: 0 auto 0;"
        >
            <h5 class="card-header">Equipamento: {{ equipment.equipment_model }}</h5>

            <div class="card-body">
                <h5 class="card-title mb-3">Nº de patrimônio: {{ equipment.patrimony }}</h5>
                <p class="card-text">Localização: {{ equipment.location|default_if_none:"---" }}</p>
                <p class="card-text">Nº de série: {{ equipment.serial_number }}</p>
                <p class="card-text">Histórico de acidentes: {{ equipment.accident_history|yesno:"Sim,Não" }}</p>
            </div>
        </div>

        <form
            action="{% url 'equipments:equipment_open_work' equipment_id=equipment.id %}"
            class="pt-3 row w-100"
            method="POST"
            style="max-width: 600px; margin: 0 auto 0;"
        >
            {% csrf_token %}

            {% for field in form %}
                <div class="mb-3">
                    <label
                        for="{{ field.id_for_label }}"
                        class="form-label"
                    >
                        {{ field.label }}
                    </label>

                    {{ field }}
                </div>
            {% endfor %}

            <div>
                <button
                    class="btn btn-lg btn-primary w-100"
                    type="submit"
                    {% if submit_disabled %} disabled {% endif %}
                >
                    ENVIAR
                </button>
            </div>
        </form>

        <p class="text-center text-muted mt-3">
            © SIGEMH – {% now "Y" %}
        </p>
    </main>
{% endblock content %}

{% block other_scripts %}
    <script>
        async function postData(route, formData) {
            return fetch(
                route,
                {
                    credentials: 'same-origin',
                    method: 'POST',
                    body: formData,
                    redirect: 'follow'
                }
            )
            .then(response => {
                if (response.redirected) {
                    document.location.reload(true)
                    return
                }
                return response.json()
                .then(data => ({
                        status: response.status,
                        data
                    })
                )
            })
        }

        const form = document.querySelector('form')
        form.addEventListener('submit', function(event) {
            event.preventDefault()
            const route = form.action
            const formData = new FormData(form)
            postData(route, formData)
            .then(response => {
                console.log(response)
                if (response.status === 200)
                    window.location.replace('/success')
                else
                    window.location.href = 'error'
            })
            .catch(error => {
                // console.log(error)
                // alert(error)
                window.history.go = ''
            })
        })
    </script>
{% endblock other_scripts %}

templates/equipments/error.html
{% extends '../partials/__base.html' %}
{% load static %}

{% block page_title %} {{ page_title }} {% endblock page_title %}

{% block content %}
    <main style="
        width: 100vw;
        height: 100vh;
        display: flex;
        align-items: center;
        justify-content: center;
        margin: 0;
        background-color: #e70000;
        color: white;
        font-size: 4rem;"
    >
        <h1>
            ERROR!!
        </h1>
    </main>
{% endblock content %}

templates/equipments/success.html
{% extends '../partials/__base.html' %}
{% load static %}

{% block page_title %} {{ page_title }} {% endblock page_title %}

{% block content %}
    <main style="
        width: 100vw;
        height: 100vh;
        display: flex;
        align-items: center;
        justify-content: center;
        margin: 0;
        background-color: #00aa00;
        color: white;
        font-size: 4rem;"
    >
        <h1>
            SUCCESS!!
        </h1>
    </main>
{% endblock content %}